/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.view;
import app.model.Deptos;
import app.dao.DeptoDao;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jvazq
 */
public class Depto extends javax.swing.JPanel {

    /**
     * Creates new form UnidaddeMedida
     */
    public Depto() {
        initComponents();
        
        ListSelectionModel cellSelectionModel = tabladepto.getSelectionModel();
    cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     DeptoDao DeptoDao = new DeptoDao();
    
        
cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
  public void valueChanged(ListSelectionEvent e) {
    String selectedData = null;

    int[] selectedRow = tabladepto.getSelectedRows();
    int[] selectedColumns = tabladepto.getSelectedColumns();

    for (int i = 0; i < selectedRow.length; i++) {
        id.setText( tabladepto.getValueAt(selectedRow[i], 0)+"");
        id.repaint();
        nombredepto.setText( tabladepto.getValueAt(selectedRow[i], 1)+"");
        nombredepto.repaint();      
       
           }
    }
     });

 DeptoDao = new DeptoDao();  
        List<Deptos> deptos=DeptoDao.buscaDeptos();
        int row=0;
        
        for(Deptos Deptos: deptos){
            tabladepto.getModel().setValueAt(Deptos.getIdDepto(), row, 0);
            tabladepto.getModel().setValueAt(Deptos.getNombreDepto(), row, 1);
           
            row++;
        }

        this.tabladepto.repaint();
        this.tabladepto.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladepto = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        nombredepto = new javax.swing.JTextField();
        modificar = new javax.swing.JButton();
        agregar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();

        jLabel1.setText("Departamento");

        tabladepto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id depto", "nombre depto"
            }
        ));
        jScrollPane1.setViewportView(tabladepto);

        jLabel2.setText("id depto");

        jLabel3.setText("nombre depto");

        id.setText("id");

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(eliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(id)
                                .addGap(161, 161, 161)
                                .addComponent(agregar)
                                .addGap(0, 4, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombredepto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(modificar))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(id)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregar)
                        .addGap(5, 5, 5)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombredepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificar))
                .addGap(44, 44, 44)
                .addComponent(eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        DeptoDao DeptoDao = new DeptoDao();
      
         
        DeptoDao.updateRegistro(
                this.nombredepto.getText(),
                Integer.parseInt(id.getText()));
                
      
         List<Deptos> deptos=DeptoDao.buscaDeptos();
        int row=0;
        
        for(Deptos Deptos: deptos){
            tabladepto.getModel().setValueAt(Deptos.getIdDepto(), row, 0);
            tabladepto.getModel().setValueAt(Deptos.getNombreDepto(), row, 1);
            
           
            row++;
        }

        this.tabladepto.repaint();
        this.tabladepto.revalidate();
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        
        DeptoDao DeptoDao = new DeptoDao();
      
         
        DeptoDao.deletRegistro(
                Integer.parseInt(id.getText()));
      
        
         DefaultTableModel dm = (DefaultTableModel) tabladepto.getModel();
int rowCount = dm.getRowCount();
//Remove rows one by one from the end of the table
for (int i = rowCount - 1; i >= 0; i--) {
            tabladepto.getModel().setValueAt("", i, 0);
            tabladepto.getModel().setValueAt("", i, 1);
}
        
        
        List<Deptos> deptos=DeptoDao.buscaDeptos();      
            int row=0;
        
        for(Deptos Deptos: deptos){
            tabladepto.getModel().setValueAt(Deptos.getIdDepto(), row, 0);
            tabladepto.getModel().setValueAt(Deptos.getNombreDepto(), row, 1);
            row++;
        }

        this.tabladepto.repaint();
        this.tabladepto.revalidate();
    }//GEN-LAST:event_eliminarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        
        DeptoDao DeptoDao = new DeptoDao();
      
         
        DeptoDao.insertaRegistro(
                this.nombredepto.getText());
                
      
         List<Deptos> deptos=DeptoDao.buscaDeptos();
        int row=0;
        
        for(Deptos Deptos: deptos){
            tabladepto.getModel().setValueAt(Deptos.getIdDepto(), row, 0);
            tabladepto.getModel().setValueAt(Deptos.getNombreDepto(), row, 1);
            
           
            row++;
        }

        this.tabladepto.repaint();
        this.tabladepto.revalidate();
    }//GEN-LAST:event_agregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombredepto;
    private javax.swing.JTable tabladepto;
    // End of variables declaration//GEN-END:variables
}
