/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package app.view;

import app.dao.RolDao;
import app.model.Rol;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jvazq
 */
public class NewJInternalFrameRoles extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrameRoles
     */
    public NewJInternalFrameRoles() {
        initComponents();
        
        ListSelectionModel cellSelectionModel = tablarol.getSelectionModel();
    cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     RolDao RolDao = new RolDao();
    
        
cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
  public void valueChanged(ListSelectionEvent e) {
    String selectedData = null;

    int[] selectedRow = tablarol.getSelectedRows();
    int[] selectedColumns = tablarol.getSelectedColumns();

    for (int i = 0; i < selectedRow.length; i++) {
        id.setText( tablarol.getValueAt(selectedRow[i], 0)+"");
        id.repaint();
        nombre.setText( tablarol.getValueAt(selectedRow[i], 1)+"");
        nombre.repaint(); 
        ocupacion.setText( tablarol.getValueAt(selectedRow[i], 2)+"");
        ocupacion.repaint();
        diasdesca.setText( tablarol.getValueAt(selectedRow[i], 3)+"");
        diasdesca.repaint();
        coloriden.setText( tablarol.getValueAt(selectedRow[i], 4)+"");
        coloriden.repaint();
        areatrabajar.setText( tablarol.getValueAt(selectedRow[i], 5)+"");
        areatrabajar.repaint();
       
           }
    }
     });

 RolDao = new RolDao();  
        List<Rol> roles=RolDao.buscaRoles();
        int row=0;
        
        for(Rol Rol: roles){
            tablarol.getModel().setValueAt(Rol.getRolId(), row, 0);
            tablarol.getModel().setValueAt(Rol.getNombreRol(), row, 1);
            tablarol.getModel().setValueAt(Rol.getOcupacion(), row, 2);
            tablarol.getModel().setValueAt(Rol.getDiasdescanso(), row, 3);
            tablarol.getModel().setValueAt(Rol.getColorident(), row, 4);
            tablarol.getModel().setValueAt(Rol.getArea(), row, 5);
           
            row++;
        }

        this.tablarol.repaint();
        this.tablarol.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablarol = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        ocupacion = new javax.swing.JTextField();
        diasdesca = new javax.swing.JTextField();
        coloriden = new javax.swing.JTextField();
        areatrabajar = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("Rol");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/imagenes/icons8-duty-64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(382, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(309, 309, 309))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        tablarol.setBackground(new java.awt.Color(255, 204, 102));
        tablarol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id rol", "nombre", "ocupacion", "dias de descanso", "color identificativo", "area a trabajar"
            }
        ));
        jScrollPane1.setViewportView(tablarol);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 800, 160));

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("id rol");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("nombre");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("ocupacion");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("dias de descanso");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("color identificativo");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("area a trabajar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 160, 240));

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));

        id.setText("id");

        nombre.setBackground(new java.awt.Color(255, 204, 51));
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        ocupacion.setBackground(new java.awt.Color(255, 204, 51));

        diasdesca.setBackground(new java.awt.Color(255, 204, 51));
        diasdesca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diasdescaActionPerformed(evt);
            }
        });

        coloriden.setBackground(new java.awt.Color(255, 204, 51));

        areatrabajar.setBackground(new java.awt.Color(255, 204, 51));

        agregar.setBackground(new java.awt.Color(255, 204, 51));
        agregar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        modificar.setBackground(new java.awt.Color(255, 204, 51));
        modificar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        eliminar.setBackground(new java.awt.Color(255, 204, 51));
        eliminar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(id)
                    .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(ocupacion)
                    .addComponent(diasdesca)
                    .addComponent(coloriden)
                    .addComponent(areatrabajar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar))
                .addGap(18, 18, 18)
                .addComponent(ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diasdesca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(coloriden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areatrabajar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminar))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 640, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void diasdescaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diasdescaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diasdescaActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        
        RolDao RolDao = new RolDao();
      
         
        RolDao.insertaRegistro(
                this.nombre.getText(),
                this.ocupacion.getText(),
                this.diasdesca.getText(),
                this.coloriden.getText(),
                this.areatrabajar.getText());
                
      
         List<Rol> roles=RolDao.buscaRoles();
        int row=0;
        
        for(Rol Rol: roles){
            tablarol.getModel().setValueAt(Rol.getRolId(), row, 0);
            tablarol.getModel().setValueAt(Rol.getNombreRol(), row, 1);
            tablarol.getModel().setValueAt(Rol.getOcupacion(), row, 2);
            tablarol.getModel().setValueAt(Rol.getDiasdescanso(), row, 3);
            tablarol.getModel().setValueAt(Rol.getColorident(), row, 4);
            tablarol.getModel().setValueAt(Rol.getArea(), row, 5);
            
           
            row++;
        }

        this.tablarol.repaint();
        this.tablarol.revalidate();
    }//GEN-LAST:event_agregarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        
        RolDao RolDao = new RolDao();
      
         
        RolDao.updateRegistro(
                this.nombre.getText(),
                this.ocupacion.getText(),
                this.diasdesca.getText(),
                this.coloriden.getText(),
                this.areatrabajar.getText(),
                Integer.parseInt(id.getText()));
                
      
         List<Rol> roles=RolDao.buscaRoles();
        int row=0;
        
        for(Rol Rol: roles){
            tablarol.getModel().setValueAt(Rol.getRolId(), row, 0);
            tablarol.getModel().setValueAt(Rol.getNombreRol(), row, 1);
            tablarol.getModel().setValueAt(Rol.getOcupacion(), row, 2);
            tablarol.getModel().setValueAt(Rol.getDiasdescanso(), row, 3);
            tablarol.getModel().setValueAt(Rol.getColorident(), row, 4);
            tablarol.getModel().setValueAt(Rol.getArea(), row, 5);
            
           
            row++;
        }

        this.tablarol.repaint();
        this.tablarol.revalidate();
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        
        RolDao RolDao = new RolDao();
      
         
        RolDao.deletRegistro(
                Integer.parseInt(id.getText()));
      
        
         DefaultTableModel dm = (DefaultTableModel) tablarol.getModel();
int rowCount = dm.getRowCount();
//Remove rows one by one from the end of the table
for (int i = rowCount - 1; i >= 0; i--) {
            tablarol.getModel().setValueAt("", i, 0);
            tablarol.getModel().setValueAt("", i, 1);
            tablarol.getModel().setValueAt("", i, 2);
            tablarol.getModel().setValueAt("", i, 3);
            tablarol.getModel().setValueAt("", i, 4);
            tablarol.getModel().setValueAt("", i, 5);
}
        
        
        List<Rol> roles=RolDao.buscaRoles();      
            int row=0;
        
        for(Rol Rol: roles){
            tablarol.getModel().setValueAt(Rol.getRolId(), row, 0);
            tablarol.getModel().setValueAt(Rol.getNombreRol(), row, 1);
            tablarol.getModel().setValueAt(Rol.getOcupacion(), row, 2);
            tablarol.getModel().setValueAt(Rol.getDiasdescanso(), row, 3);
            tablarol.getModel().setValueAt(Rol.getColorident(), row, 4);
            tablarol.getModel().setValueAt(Rol.getArea(), row, 5);
            row++;
        }

        this.tablarol.repaint();
        this.tablarol.revalidate();
    }//GEN-LAST:event_eliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTextField areatrabajar;
    private javax.swing.JTextField coloriden;
    private javax.swing.JTextField diasdesca;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField ocupacion;
    private javax.swing.JTable tablarol;
    // End of variables declaration//GEN-END:variables
}
