/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package app.view;

import app.dao.UserDao;
import app.model.Usuario;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jvazq
 */
public class NewJInternalFrameUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrameUsuarios
     */
    public NewJInternalFrameUsuarios() {
        initComponents();
        
         ListSelectionModel cellSelectionModel = tablaUsuarios.getSelectionModel();
    cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     UserDao userDao = new UserDao();
     //DeptoDao deptodao = new DeptoDao();
        
cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
  public void valueChanged(ListSelectionEvent e) {
    String selectedData = null;

    int[] selectedRow = tablaUsuarios.getSelectedRows();
    int[] selectedColumns = tablaUsuarios.getSelectedColumns();

    for (int i = 0; i < selectedRow.length; i++) {
        
        nombre.setText( tablaUsuarios.getValueAt(selectedRow[i], 0)+"");
        nombre.repaint();
        ApellidoPa.setText( tablaUsuarios.getValueAt(selectedRow[i], 1)+"");
        ApellidoPa.repaint();
        ApellidoMa.setText( tablaUsuarios.getValueAt(selectedRow[i], 2)+"");
        ApellidoMa.repaint();
        Contrasena.setText( tablaUsuarios.getValueAt(selectedRow[i], 3)+"");
        Contrasena.repaint();
        Rol.setText( tablaUsuarios.getValueAt(selectedRow[i], 4)+"");
        Rol.repaint();
        Usuario.setText( tablaUsuarios.getValueAt(selectedRow[i], 5)+"");
        Usuario.repaint();
        id.setText( tablaUsuarios.getValueAt(selectedRow[i], 6)+"");
        id.repaint();

    }
    }
     });

 userDao = new UserDao();  
        List<Usuario> usuarios=userDao.buscaUsuarios();
        int row=0;
        
        for(Usuario usuario: usuarios){
            tablaUsuarios.getModel().setValueAt(usuario.getNombre(), row, 0);
            tablaUsuarios.getModel().setValueAt(usuario.getApellidoPa(), row, 1);
            tablaUsuarios.getModel().setValueAt(usuario.getApellidoMa(), row, 2);
            tablaUsuarios.getModel().setValueAt(usuario.getContrasena(), row, 3);
            tablaUsuarios.getModel().setValueAt(usuario.getRolId(), row, 4);
            tablaUsuarios.getModel().setValueAt(usuario.getUsuario(), row, 5);
            tablaUsuarios.getModel().setValueAt(usuario.getIdUsuario(), row, 6);
           
            row++;
        }

        this.tablaUsuarios.repaint();
        this.tablaUsuarios.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        ApellidoPa = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        ApellidoMa = new javax.swing.JTextField();
        Rol = new javax.swing.JTextField();
        Usuario = new javax.swing.JTextField();
        Contrasena = new javax.swing.JTextField();
        actualizar = new javax.swing.JButton();
        crear = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Apellido materno");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("Contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Rol");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Usuario");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("Id");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Apellido paterno");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 270));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        id.setText("id");

        ApellidoPa.setBackground(new java.awt.Color(204, 204, 255));
        ApellidoPa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoPaActionPerformed(evt);
            }
        });

        nombre.setBackground(new java.awt.Color(204, 204, 255));
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        ApellidoMa.setBackground(new java.awt.Color(204, 204, 255));
        ApellidoMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoMaActionPerformed(evt);
            }
        });

        Rol.setBackground(new java.awt.Color(204, 204, 255));
        Rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RolActionPerformed(evt);
            }
        });

        Usuario.setBackground(new java.awt.Color(204, 204, 255));
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });

        Contrasena.setBackground(new java.awt.Color(204, 204, 255));
        Contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrasenaActionPerformed(evt);
            }
        });

        actualizar.setBackground(new java.awt.Color(204, 204, 255));
        actualizar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        crear.setBackground(new java.awt.Color(204, 204, 255));
        crear.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        borrar.setBackground(new java.awt.Color(204, 204, 255));
        borrar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/imagenes/icons8-usuario-30.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("Usuarios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(id, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(106, 106, 106))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Rol, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ApellidoMa, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ApellidoPa, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(crear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(23, 23, 23)
                        .addComponent(id))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ApellidoPa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApellidoMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crear))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(borrar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 570, 270));

        tablaUsuarios.setBackground(new java.awt.Color(204, 204, 255));
        tablaUsuarios.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "ApellidoPa", "ApellidoMa", "Contraseña", "Rol", "Usuario", "Id"
            }
        ));
        jScrollPane1.setViewportView(tablaUsuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 270, 790, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ApellidoPaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoPaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoPaActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void ApellidoMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoMaActionPerformed

    private void RolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RolActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void ContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContrasenaActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        // TODO add your handling code here:
        
        UserDao userDao = new UserDao();
      
         
        userDao.insertaRegistro(
                 this.ApellidoMa.getText(),
                this.ApellidoPa.getText(),
                this.nombre.getText(),
                Integer.parseInt(this.Rol.getText()), 
                this.Usuario.getText(), 
                this.Contrasena.getText());
      
         List<Usuario> usuarios=userDao.buscaUsuarios();
        int row=0;
        
        for(Usuario usuario: usuarios){
            tablaUsuarios.getModel().setValueAt(usuario.getNombre(), row, 0);
            tablaUsuarios.getModel().setValueAt(usuario.getApellidoPa(), row, 1);
            tablaUsuarios.getModel().setValueAt(usuario.getApellidoMa(), row, 2);
            tablaUsuarios.getModel().setValueAt(usuario.getContrasena(), row, 3);
            tablaUsuarios.getModel().setValueAt(usuario.getRolId(), row, 4);
            tablaUsuarios.getModel().setValueAt(usuario.getUsuario(), row, 5);
            tablaUsuarios.getModel().setValueAt(usuario.getIdUsuario(), row, 6);
           
            row++;
        }

        this.tablaUsuarios.repaint();
        this.tablaUsuarios.revalidate();
    }//GEN-LAST:event_crearActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
        
        UserDao userDao = new UserDao();
      
         
        userDao.updateRegistro(
                 this.ApellidoMa.getText(),
                this.ApellidoPa.getText(),
                this.nombre.getText(),
                Integer.parseInt(this.Rol.getText()), 
                this.Usuario.getText(), 
                this.Contrasena.getText(),
                Integer.parseInt(id.getText()));
      
         List<Usuario> usuarios=userDao.buscaUsuarios();
        int row=0;
        
        for(Usuario usuario: usuarios){
            tablaUsuarios.getModel().setValueAt(usuario.getNombre(), row, 0);
            tablaUsuarios.getModel().setValueAt(usuario.getApellidoPa(), row, 1);
            tablaUsuarios.getModel().setValueAt(usuario.getApellidoMa(), row, 2);
            tablaUsuarios.getModel().setValueAt(usuario.getContrasena(), row, 3);
            tablaUsuarios.getModel().setValueAt(usuario.getRolId(), row, 4);
            tablaUsuarios.getModel().setValueAt(usuario.getUsuario(), row, 5);
            tablaUsuarios.getModel().setValueAt(usuario.getIdUsuario(), row, 6);
           
            row++;
        }

        this.tablaUsuarios.repaint();
        this.tablaUsuarios.revalidate();
    }//GEN-LAST:event_actualizarActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
        
         UserDao userDao = new UserDao();
      
         
        userDao.deletRegistro(
                Integer.parseInt(id.getText()));
      
        
         DefaultTableModel dm = (DefaultTableModel) tablaUsuarios.getModel();
int rowCount = dm.getRowCount();
//Remove rows one by one from the end of the table
for (int i = rowCount - 1; i >= 0; i--) {
     tablaUsuarios.getModel().setValueAt("", i, 0);
            tablaUsuarios.getModel().setValueAt("", i, 1);
            tablaUsuarios.getModel().setValueAt("", i, 2);
            tablaUsuarios.getModel().setValueAt("", i, 3);
            tablaUsuarios.getModel().setValueAt("", i, 4);
            tablaUsuarios.getModel().setValueAt("", i, 5);
            tablaUsuarios.getModel().setValueAt("", i, 6);
}
        
        
         List<Usuario> usuarios=userDao.buscaUsuarios();
         
        int row=0;
        
        for(Usuario usuario: usuarios){
            tablaUsuarios.getModel().setValueAt(usuario.getNombre(), row, 0);
            tablaUsuarios.getModel().setValueAt(usuario.getApellidoPa(), row, 1);
            tablaUsuarios.getModel().setValueAt(usuario.getApellidoMa(), row, 2);
            tablaUsuarios.getModel().setValueAt(usuario.getContrasena(), row, 3);
            tablaUsuarios.getModel().setValueAt(usuario.getRolId(), row, 4);
            tablaUsuarios.getModel().setValueAt(usuario.getUsuario(), row, 5);
            tablaUsuarios.getModel().setValueAt(usuario.getIdUsuario(), row, 6);
           
            row++;
        }

        this.tablaUsuarios.repaint();
        this.tablaUsuarios.revalidate();
    }//GEN-LAST:event_borrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoMa;
    private javax.swing.JTextField ApellidoPa;
    private javax.swing.JTextField Contrasena;
    private javax.swing.JTextField Rol;
    private javax.swing.JTextField Usuario;
    private javax.swing.JButton actualizar;
    private javax.swing.JButton borrar;
    private javax.swing.JButton crear;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}
