/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package app.view;

import app.dao.ProveedoresDao;
import app.model.Proveedor;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jvazq
 */
public class NewJInternalFrameProveedores extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrameProveedores
     */
    public NewJInternalFrameProveedores() {
        initComponents();
        ListSelectionModel cellSelectionModel = tablaproveedores.getSelectionModel();
    cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     ProveedoresDao ProveedoresDao = new ProveedoresDao();
    
        
cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
  public void valueChanged(ListSelectionEvent e) {
    String selectedData = null;

    int[] selectedRow = tablaproveedores.getSelectedRows();
    int[] selectedColumns = tablaproveedores.getSelectedColumns();

    for (int i = 0; i < selectedRow.length; i++) {
        id.setText( tablaproveedores.getValueAt(selectedRow[i], 0)+"");
        id.repaint();
        nombre.setText( tablaproveedores.getValueAt(selectedRow[i], 1)+"");
        nombre.repaint();      
        origen.setText( tablaproveedores.getValueAt(selectedRow[i], 2)+"");
        origen.repaint();
        productos.setText(tablaproveedores.getValueAt(selectedRow[i], 3)+"");
        productos.repaint();
        tipomer.setText(tablaproveedores.getValueAt(selectedRow[i], 4)+"");
        tipomer.repaint();
        numerotel.setText( tablaproveedores.getValueAt(selectedRow[i], 5)+"");
        numerotel.repaint();
        diasentrega.setText(tablaproveedores.getValueAt(selectedRow[i], 6)+"");
        diasentrega.repaint();
        numeroalmacen.setText(tablaproveedores.getValueAt(selectedRow[i], 7)+"");
        numeroalmacen.repaint();
       
    }
    }
     });

 ProveedoresDao = new ProveedoresDao();  
        List<Proveedor> proveedores=ProveedoresDao.buscaProveedor();
        int row=0;
        
        for(Proveedor Proveedor: proveedores){
             tablaproveedores.getModel().setValueAt(Proveedor.getIdproveedor(), row, 0);
            tablaproveedores.getModel().setValueAt(Proveedor.getNombre(), row, 1);
            tablaproveedores.getModel().setValueAt(Proveedor.getOrigen(), row, 2);
            tablaproveedores.getModel().setValueAt(Proveedor.getProductos(), row, 3);
            tablaproveedores.getModel().setValueAt(Proveedor.getTipomerca(), row, 4);
            tablaproveedores.getModel().setValueAt(Proveedor.getNumerotel(), row, 5);
            tablaproveedores.getModel().setValueAt(Proveedor.getDiasentrega(), row, 6);
            tablaproveedores.getModel().setValueAt(Proveedor.getNumeroalma(), row, 7);
           
           
            row++;
        }

        this.tablaproveedores.repaint();
        this.tablaproveedores.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaproveedores = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        numeroalmacen = new javax.swing.JTextField();
        productos = new javax.swing.JTextField();
        tipomer = new javax.swing.JTextField();
        numerotel = new javax.swing.JTextField();
        diasentrega = new javax.swing.JTextField();
        origen = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        agregar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("Proveedores");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/imagenes/icons8-camión-50.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(335, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(246, 246, 246))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 80));

        tablaproveedores.setBackground(new java.awt.Color(204, 204, 255));
        tablaproveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "proveedor id", "nombre", "origen", "productos", "tipo de mercancia", "numero tel", "dias de entrega", "numero de almacen"
            }
        ));
        jScrollPane1.setViewportView(tablaproveedores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 304, 788, 160));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel2.setText("proveedor id");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setText("nombre ");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("origen");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setText("productos");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel6.setText("numero telefonico");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel7.setText("tipo de mercancia");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel8.setText("dias que entrega");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel9.setText("numero de almacen ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 170, 230));

        id.setText("id");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        nombre.setBackground(new java.awt.Color(204, 204, 255));
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 270, -1));

        numeroalmacen.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(numeroalmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 270, -1));

        productos.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 270, -1));

        tipomer.setBackground(new java.awt.Color(204, 204, 255));
        tipomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipomerActionPerformed(evt);
            }
        });
        getContentPane().add(tipomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 270, -1));

        numerotel.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(numerotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 270, -1));

        diasentrega.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(diasentrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 270, -1));

        origen.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(origen, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 270, -1));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        agregar.setBackground(new java.awt.Color(204, 204, 255));
        agregar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        modificar.setBackground(new java.awt.Color(204, 204, 255));
        modificar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        eliminar.setBackground(new java.awt.Color(204, 204, 255));
        eliminar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(502, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(agregar)
                .addGap(38, 38, 38)
                .addComponent(modificar)
                .addGap(37, 37, 37)
                .addComponent(eliminar)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 620, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void tipomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipomerActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        ProveedoresDao ProveedoresDao = new ProveedoresDao();
      
         
        ProveedoresDao.updateRegistro(
               
                
                this.nombre.getText(),
                this.origen.getText(),
                this.productos.getText(),
                this.tipomer.getText(),
                Integer.parseInt(this.numerotel.getText()),
                this.diasentrega.getText(),
                Integer.parseInt(this.numeroalmacen.getText()),
                
                
                Integer.parseInt(id.getText()));
      
          List<Proveedor> proveedores=ProveedoresDao.buscaProveedor();
        int row=0;
        
         for(Proveedor Proveedor: proveedores){
            tablaproveedores.getModel().setValueAt(Proveedor.getIdproveedor(), row, 0);
            tablaproveedores.getModel().setValueAt(Proveedor.getNombre(), row, 1);
            tablaproveedores.getModel().setValueAt(Proveedor.getOrigen(), row, 2);
            tablaproveedores.getModel().setValueAt(Proveedor.getProductos(), row, 3);
            tablaproveedores.getModel().setValueAt(Proveedor.getTipomerca(), row, 4);
            tablaproveedores.getModel().setValueAt(Proveedor.getNumerotel(), row, 5);
            tablaproveedores.getModel().setValueAt(Proveedor.getDiasentrega(), row, 6);
            tablaproveedores.getModel().setValueAt(Proveedor.getNumeroalma(), row, 7);
           
           
            row++;
        }

        this.tablaproveedores.repaint();
        this.tablaproveedores.revalidate();
        
        
    }//GEN-LAST:event_modificarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        ProveedoresDao ProveedoresDao = new ProveedoresDao();
      
         
        ProveedoresDao.insertaRegistro(
               
                
                this.nombre.getText(),
                this.origen.getText(),
                this.productos.getText(),
                this.tipomer.getText(),
                Integer.parseInt(this.numerotel.getText()),
                this.diasentrega.getText(),
                Integer.parseInt(this.numeroalmacen.getText()));
                
                
      
          List<Proveedor> proveedores=ProveedoresDao.buscaProveedor();
        int row=0;
        
         for(Proveedor Proveedor: proveedores){
            tablaproveedores.getModel().setValueAt(Proveedor.getIdproveedor(), row, 0);
            tablaproveedores.getModel().setValueAt(Proveedor.getNombre(), row, 1);
            tablaproveedores.getModel().setValueAt(Proveedor.getOrigen(), row, 2);
            tablaproveedores.getModel().setValueAt(Proveedor.getProductos(), row, 3);
            tablaproveedores.getModel().setValueAt(Proveedor.getTipomerca(), row, 4);
            tablaproveedores.getModel().setValueAt(Proveedor.getNumerotel(), row, 5);
            tablaproveedores.getModel().setValueAt(Proveedor.getDiasentrega(), row, 6);
            tablaproveedores.getModel().setValueAt(Proveedor.getNumeroalma(), row, 7);
           
           
            row++;
        }

        this.tablaproveedores.repaint();
        this.tablaproveedores.revalidate();
    }//GEN-LAST:event_agregarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        ProveedoresDao ProveedoresDao = new ProveedoresDao();
      
         
        ProveedoresDao.deletRegistro(
                Integer.parseInt(id.getText()));
      
        
         DefaultTableModel dm = (DefaultTableModel) tablaproveedores.getModel();
int rowCount = dm.getRowCount();
//Remove rows one by one from the end of the table
for (int i = rowCount - 1; i >= 0; i--) {
            tablaproveedores.getModel().setValueAt("", i, 0);
            tablaproveedores.getModel().setValueAt("", i, 1);
            tablaproveedores.getModel().setValueAt("", i, 2);
            tablaproveedores.getModel().setValueAt("", i, 3);
            tablaproveedores.getModel().setValueAt("", i, 4);
            tablaproveedores.getModel().setValueAt("", i, 5);
            tablaproveedores.getModel().setValueAt("", i, 6);
            tablaproveedores.getModel().setValueAt("", i, 7);
            
            List<Proveedor> proveedores=ProveedoresDao.buscaProveedor();
        int row=0;
        
         for(Proveedor Proveedor: proveedores){
            tablaproveedores.getModel().setValueAt(Proveedor.getIdproveedor(), row, 0);
            tablaproveedores.getModel().setValueAt(Proveedor.getNombre(), row, 1);
            tablaproveedores.getModel().setValueAt(Proveedor.getOrigen(), row, 2);
            tablaproveedores.getModel().setValueAt(Proveedor.getProductos(), row, 3);
            tablaproveedores.getModel().setValueAt(Proveedor.getTipomerca(), row, 4);
            tablaproveedores.getModel().setValueAt(Proveedor.getNumerotel(), row, 5);
            tablaproveedores.getModel().setValueAt(Proveedor.getDiasentrega(), row, 6);
            tablaproveedores.getModel().setValueAt(Proveedor.getNumeroalma(), row, 7);
           
           
            row++;
        }

        this.tablaproveedores.repaint();
        this.tablaproveedores.revalidate();
     
}
    }//GEN-LAST:event_eliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTextField diasentrega;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numeroalmacen;
    private javax.swing.JTextField numerotel;
    private javax.swing.JTextField origen;
    private javax.swing.JTextField productos;
    private javax.swing.JTable tablaproveedores;
    private javax.swing.JTextField tipomer;
    // End of variables declaration//GEN-END:variables
}
