/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package app.view;

import app.dao.ProductoDao;
import app.model.Producto;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jvazq
 */
public class NewJInternalFrameInventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrameInventario
     */
    public NewJInternalFrameInventario() {
        initComponents();
        ListSelectionModel cellSelectionModel = tablainventario.getSelectionModel();
    cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     ProductoDao ProductoDao = new ProductoDao();
     //DeptoDao deptodao = new DeptoDao();
        
cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
  public void valueChanged(ListSelectionEvent e) {
    String selectedData = null;

    int[] selectedRow = tablainventario.getSelectedRows();
    int[] selectedColumns = tablainventario.getSelectedColumns();

    for (int i = 0; i < selectedRow.length; i++) {
        id.setText( tablainventario.getValueAt(selectedRow[i], 0)+"");
        id.repaint();
        nombre.setText( tablainventario.getValueAt(selectedRow[i], 1)+"");
        nombre.repaint();      
        cantidad.setText( tablainventario.getValueAt(selectedRow[i], 2)+"");
        cantidad.repaint();
        precio.setText(tablainventario.getValueAt(selectedRow[i], 3)+"");
        precio.repaint();
        area.setText(tablainventario.getValueAt(selectedRow[i], 4)+"");
        area.repaint();
        tipo.setText(tablainventario.getValueAt(selectedRow[i], 5)+"");
        tipo.repaint();
        unidad.setText(tablainventario.getValueAt(selectedRow[i], 6)+"");
        unidad.repaint();
        clave.setText(tablainventario.getValueAt(selectedRow[i], 7)+"");
        clave.repaint();
        descripcion.setText(tablainventario.getValueAt(selectedRow[i], 8)+"");
        descripcion.repaint();
        
        
    }
    }
     });

 ProductoDao = new ProductoDao();  
        List<Producto> productos=ProductoDao.buscaProducto();
        int row=0;
        
        for(Producto producto: productos){
     tablainventario.getModel().setValueAt(producto.getIdProducto(), row, 0);
            tablainventario.getModel().setValueAt(producto.getNombre(), row, 1);
            tablainventario.getModel().setValueAt(producto.getCantidad(), row, 2);
            tablainventario.getModel().setValueAt(producto.getPrecio(), row, 3);
            tablainventario.getModel().setValueAt(producto.getArea(), row, 4);
            tablainventario.getModel().setValueAt(producto.getTipo(), row, 5);
            tablainventario.getModel().setValueAt(producto.getUnidaMedida(), row, 6);
            tablainventario.getModel().setValueAt(producto.getClave(), row, 7);
            tablainventario.getModel().setValueAt(producto.getDescripcion(), row, 8);
           
            row++;
        }

        this.tablainventario.repaint();
        this.tablainventario.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablainventario = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nombrer = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nombre = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        area = new javax.swing.JTextField();
        tipo = new javax.swing.JTextField();
        unidad = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        clave = new javax.swing.JTextField();
        descripcion = new javax.swing.JTextField();

        jButton3.setText("jButton3");

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablainventario.setBackground(new java.awt.Color(255, 204, 153));
        tablainventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id producto", "Nombre", "Cantidad", "Precio", "Area", " Tipo", "Unidadmed", "Clave", "Descripcion"
            }
        ));
        tablainventario.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tablainventario);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 790, 140));

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("Inventario");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/imagenes/icons8-producto-nuevo-50.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 70));

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("idproducto");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 0, -1, 18));

        nombrer.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        nombrer.setText("Nombre");
        jPanel2.add(nombrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 24, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("Cantidad");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 56, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Precio");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 88, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Area");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 114, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("Tipo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 146, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setText("Unidad de medida");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 178, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel10.setText("Clave");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 216, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel11.setText("Descripcion");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 258, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 170, 310));

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre.setBackground(new java.awt.Color(255, 204, 153));
        jPanel3.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 31, 300, -1));

        cantidad.setBackground(new java.awt.Color(255, 204, 153));
        jPanel3.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, 300, -1));

        precio.setBackground(new java.awt.Color(255, 204, 153));
        jPanel3.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 88, 300, -1));

        area.setBackground(new java.awt.Color(255, 204, 153));
        jPanel3.add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 116, 300, -1));

        tipo.setBackground(new java.awt.Color(255, 204, 153));
        jPanel3.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 144, 300, -1));

        unidad.setBackground(new java.awt.Color(255, 204, 153));
        jPanel3.add(unidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 178, 300, -1));

        id.setText("id");
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        agregar.setBackground(new java.awt.Color(255, 204, 153));
        agregar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jPanel3.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 31, 89, -1));

        modificar.setBackground(new java.awt.Color(255, 204, 153));
        modificar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jPanel3.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 102, -1, -1));

        eliminar.setBackground(new java.awt.Color(255, 204, 153));
        eliminar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel3.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 206, 89, -1));

        clave.setBackground(new java.awt.Color(255, 204, 153));
        clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveActionPerformed(evt);
            }
        });
        jPanel3.add(clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 218, 300, -1));

        descripcion.setBackground(new java.awt.Color(255, 204, 153));
        jPanel3.add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 258, 300, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 620, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        
        
        if(
                this.nombre.getText().isBlank()
                ||this.precio.getText().isBlank()
                ||this.cantidad.getText().isBlank() 
                ||this.area.getText().isBlank() 
                ||this.tipo.getText().isBlank()
                ||this.unidad.getText().isBlank()
                ||this.clave.getText().isBlank()
                ||this.descripcion.getText().isBlank()
                ){
        String message = "No dejar campos en blanco";
    JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.ERROR_MESSAGE);
        
        }else{
        
        try{
            Float.parseFloat(this.precio.getText());
         }catch(NumberFormatException nfe){
           String message = "el precio debe ser numerico";
    JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.ERROR_MESSAGE);
         }
        
        try{
           Integer.parseInt(this.cantidad.getText());
         }catch(NumberFormatException nfe){
           String message = "La cantidad debe ser numerico";
    JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.ERROR_MESSAGE);
         }    
            
        ProductoDao ProductoDao = new ProductoDao();
      
         
        ProductoDao.insertaRegistro(
                this.nombre.getText(),
                Float.parseFloat(this.precio.getText()),
                Integer.parseInt(this.cantidad.getText()), 
                this.area.getText(), 
                this.tipo.getText(),
                this.unidad.getText(),
                this.clave.getText(),
                this.descripcion.getText());
      
         List<Producto> productos=ProductoDao.buscaProducto();
        int row=0;
        
        for(Producto producto: productos){
            tablainventario.getModel().setValueAt(producto.getIdProducto(), row, 0);
            tablainventario.getModel().setValueAt(producto.getNombre(), row, 1);
            tablainventario.getModel().setValueAt(producto.getCantidad(), row, 2);
            tablainventario.getModel().setValueAt(producto.getPrecio(), row, 3);
            tablainventario.getModel().setValueAt(producto.getArea(), row, 4);
            tablainventario.getModel().setValueAt(producto.getTipo(), row, 5);
            tablainventario.getModel().setValueAt(producto.getUnidaMedida(), row, 6);
            tablainventario.getModel().setValueAt(producto.getClave(), row, 7);
            tablainventario.getModel().setValueAt(producto.getDescripcion(), row, 8);
           
            row++;
        }

        this.tablainventario.repaint();
        this.tablainventario.revalidate();
        }
    }//GEN-LAST:event_agregarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        
        if(
                this.nombre.getText().isBlank()
                ||this.precio.getText().isBlank()
                ||this.cantidad.getText().isBlank() 
                ||this.area.getText().isBlank() 
                ||this.tipo.getText().isBlank()
                ||this.unidad.getText().isBlank()
                ||this.clave.getText().isBlank()
                ||this.descripcion.getText().isBlank()
                ){
        String message = "No dejar campos en blanco";
    JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.ERROR_MESSAGE);
        
        }else{
        
        try{
            Float.parseFloat(this.precio.getText());
         }catch(NumberFormatException nfe){
           String message = "el precio debe ser numerico";
    JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.ERROR_MESSAGE);
         }
        
        try{
           Integer.parseInt(this.cantidad.getText());
         }catch(NumberFormatException nfe){
           String message = "La cantidad debe ser numerico";
    JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.ERROR_MESSAGE);
         }
        ProductoDao ProductoDao = new ProductoDao();
      
         
        ProductoDao.updateRegistro(
                this.nombre.getText(),
                Float.parseFloat(this.precio.getText()),
                Integer.parseInt(this.cantidad.getText()), 
                this.area.getText(), 
                this.tipo.getText(),
                this.unidad.getText(),
                this.clave.getText(),
                this.descripcion.getText(),
                Integer.parseInt(id.getText()));
      
         List<Producto> productos=ProductoDao.buscaProducto();
        int row=0;
        
        for(Producto producto: productos){
            tablainventario.getModel().setValueAt(producto.getIdProducto(), row, 0);
            tablainventario.getModel().setValueAt(producto.getNombre(), row, 1);
            tablainventario.getModel().setValueAt(producto.getCantidad(), row, 2);
            tablainventario.getModel().setValueAt(producto.getPrecio(), row, 3);
            tablainventario.getModel().setValueAt(producto.getArea(), row, 4);
            tablainventario.getModel().setValueAt(producto.getTipo(), row, 5);
            tablainventario.getModel().setValueAt(producto.getUnidaMedida(), row, 6);
            tablainventario.getModel().setValueAt(producto.getClave(), row, 7);
            tablainventario.getModel().setValueAt(producto.getDescripcion(), row, 8);
           
            row++;
        }

        this.tablainventario.repaint();
        this.tablainventario.revalidate();
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        
        ProductoDao ProductoDao = new ProductoDao();
      
         
        ProductoDao.deletRegistro(
                Integer.parseInt(id.getText()));
      
        
         DefaultTableModel dm = (DefaultTableModel) tablainventario.getModel();
int rowCount = dm.getRowCount();
//Remove rows one by one from the end of the table
for (int i = rowCount - 1; i >= 0; i--) {
     tablainventario.getModel().setValueAt("", i, 0);
            tablainventario.getModel().setValueAt("", i, 1);
            tablainventario.getModel().setValueAt("", i, 2);
            tablainventario.getModel().setValueAt("", i, 3);
            tablainventario.getModel().setValueAt("", i, 4);
            tablainventario.getModel().setValueAt("", i, 5);
            tablainventario.getModel().setValueAt("", i, 6);
            tablainventario.getModel().setValueAt("", i, 7);
            tablainventario.getModel().setValueAt("", i, 8);
}
        
        
         List<Producto> productos=ProductoDao.buscaProducto();
        int row=0;
        
        for(Producto producto: productos){
            tablainventario.getModel().setValueAt(producto.getIdProducto(), row, 0);
            tablainventario.getModel().setValueAt(producto.getNombre(), row, 1);
            tablainventario.getModel().setValueAt(producto.getCantidad(), row, 2);
            tablainventario.getModel().setValueAt(producto.getPrecio(), row, 3);
            tablainventario.getModel().setValueAt(producto.getArea(), row, 4);
            tablainventario.getModel().setValueAt(producto.getTipo(), row, 5);
            tablainventario.getModel().setValueAt(producto.getUnidaMedida(), row, 6);
            tablainventario.getModel().setValueAt(producto.getClave(), row, 7);
            tablainventario.getModel().setValueAt(producto.getDescripcion(), row, 8);
           
            row++;
        }

        this.tablainventario.repaint();
        this.tablainventario.revalidate();
    }//GEN-LAST:event_eliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTextField area;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField clave;
    private javax.swing.JTextField descripcion;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel nombrer;
    private javax.swing.JTextField precio;
    private javax.swing.JTable tablainventario;
    private javax.swing.JTextField tipo;
    private javax.swing.JTextField unidad;
    // End of variables declaration//GEN-END:variables
}
