/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package app.view;

import app.dao.UnidadmedDao;
import app.model.Unidaddemedida;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jvazq
 */
public class NewJInternalFrameudm extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrameudm
     */
    public NewJInternalFrameudm() {
        initComponents();
        
        ListSelectionModel cellSelectionModel = tablaudm.getSelectionModel();
    cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     UnidadmedDao UnidadmedDao = new UnidadmedDao();
     //DeptoDao deptodao = new DeptoDao();
        
cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
  public void valueChanged(ListSelectionEvent e) {
    String selectedData = null;

    int[] selectedRow = tablaudm.getSelectedRows();
    int[] selectedColumns = tablaudm.getSelectedColumns();

    for (int i = 0; i < selectedRow.length; i++) {
         id.setText( tablaudm.getValueAt(selectedRow[i], 0)+"");
        id.repaint();
        nombre.setText( tablaudm.getValueAt(selectedRow[i], 1)+"");
        nombre.repaint();
        unidadmax.setText( tablaudm.getValueAt(selectedRow[i], 2)+"");
        unidadmax.repaint();
        unidadmini.setText( tablaudm.getValueAt(selectedRow[i], 3)+"");
        unidadmini.repaint();
        lugarmed.setText( tablaudm.getValueAt(selectedRow[i], 4)+"");
        lugarmed.repaint();
        fechareg.setText( tablaudm.getValueAt(selectedRow[i], 5)+"");
        fechareg.repaint();
        areaentrega.setText( tablaudm.getValueAt(selectedRow[i], 6)+"");
        areaentrega.repaint();
        

    }
    }
     });

 UnidadmedDao = new UnidadmedDao();  
        List<Unidaddemedida> unidades=UnidadmedDao.buscaUnidades();
        int row=0;
        
        for(Unidaddemedida Unidaddemedida: unidades){
            tablaudm.getModel().setValueAt(Unidaddemedida.getIdUm(), row, 0);
            tablaudm.getModel().setValueAt(Unidaddemedida.getTipoDeMedida(), row, 1);
            tablaudm.getModel().setValueAt(Unidaddemedida.getUnidadmaxima(), row, 2);
            tablaudm.getModel().setValueAt(Unidaddemedida.getUnidadminima(), row, 3);
            tablaudm.getModel().setValueAt(Unidaddemedida.getLugarmed(), row, 4);
            tablaudm.getModel().setValueAt(Unidaddemedida.getFechareg(), row, 5);
            tablaudm.getModel().setValueAt(Unidaddemedida.getAreaentrega(), row, 6);
           
            row++;
        }

        this.tablaudm.repaint();
        this.tablaudm.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaudm = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        areaentrega = new javax.swing.JTextField();
        fechareg = new javax.swing.JTextField();
        lugarmed = new javax.swing.JTextField();
        unidadmini = new javax.swing.JTextField();
        unidadmax = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel9.setText("Unidad de Medida");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 17, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/imagenes/icons8-regla-48.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        tablaudm.setBackground(new java.awt.Color(255, 204, 204));
        tablaudm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id udm", "nombre", "unidad maxima ", "unidad minima", "lugar de medicion", "fecha de registro"
            }
        ));
        jScrollPane1.setViewportView(tablaudm);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 290, 790, 180));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("id udm");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("unidad maxima de venta ");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("unidad minima de venta");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("lugar de medicion ");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("fecha de registro");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("area de entrega");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, 230));

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 153, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        id.setText("id");

        areaentrega.setBackground(new java.awt.Color(255, 153, 153));

        fechareg.setBackground(new java.awt.Color(255, 153, 153));

        lugarmed.setBackground(new java.awt.Color(255, 153, 153));

        unidadmini.setBackground(new java.awt.Color(255, 153, 153));

        unidadmax.setBackground(new java.awt.Color(255, 153, 153));

        nombre.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechareg, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lugarmed, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unidadmini, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id)
                            .addComponent(areaentrega, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(unidadmax, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(39, 39, 39)
                        .addComponent(jButton2)
                        .addGap(38, 38, 38)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unidadmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(unidadmini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lugarmed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechareg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addComponent(areaentrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 590, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        UnidadmedDao UnidadmedDao = new UnidadmedDao();
      
         
        UnidadmedDao.insertaRegistro(
               
                this.nombre.getText(),
                this.unidadmax.getText(),
                this.unidadmini.getText(),
                this.lugarmed.getText(),
                this.fechareg.getText(), 
                this.areaentrega.getText());
      
         List<Unidaddemedida> unidades=UnidadmedDao.buscaUnidades();
        int row=0;
        
        for(Unidaddemedida unidaddemedida: unidades){
            tablaudm.getModel().setValueAt(unidaddemedida.getIdUm(), row, 0);
            tablaudm.getModel().setValueAt(unidaddemedida.getTipoDeMedida(), row, 1);
            tablaudm.getModel().setValueAt(unidaddemedida.getUnidadmaxima(), row, 2);
            tablaudm.getModel().setValueAt(unidaddemedida.getUnidadminima(), row, 3);
            tablaudm.getModel().setValueAt(unidaddemedida.getLugarmed(), row, 4);
            tablaudm.getModel().setValueAt(unidaddemedida.getFechareg(), row, 5);
            tablaudm.getModel().setValueAt(unidaddemedida.getAreaentrega(), row, 6);
           
            row++;
        }

        this.tablaudm.repaint();
        this.tablaudm.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        UnidadmedDao UnidadmedDao = new UnidadmedDao();
      
         
        UnidadmedDao.updateRegistro(
               
                this.nombre.getText(),
                this.unidadmax.getText(),
                this.unidadmini.getText(),
                this.lugarmed.getText(),
                this.fechareg.getText(), 
                this.areaentrega.getText(),
                Integer.parseInt(id.getText()));
      
         List<Unidaddemedida> unidades=UnidadmedDao.buscaUnidades();
        int row=0;
        
        for(Unidaddemedida unidaddemedida: unidades){
            tablaudm.getModel().setValueAt(unidaddemedida.getIdUm(), row, 0);
            tablaudm.getModel().setValueAt(unidaddemedida.getTipoDeMedida(), row, 1);
            tablaudm.getModel().setValueAt(unidaddemedida.getUnidadmaxima(), row, 2);
            tablaudm.getModel().setValueAt(unidaddemedida.getUnidadminima(), row, 3);
            tablaudm.getModel().setValueAt(unidaddemedida.getLugarmed(), row, 4);
            tablaudm.getModel().setValueAt(unidaddemedida.getFechareg(), row, 5);
            tablaudm.getModel().setValueAt(unidaddemedida.getAreaentrega(), row, 6);
           
            row++;
        }

        this.tablaudm.repaint();
        this.tablaudm.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        UnidadmedDao UnidadmedDao = new UnidadmedDao();
      
         
        UnidadmedDao.deletRegistro(
                Integer.parseInt(id.getText()));
        
         DefaultTableModel dm = (DefaultTableModel) tablaudm.getModel();
int rowCount = dm.getRowCount();
//Remove rows one by one from the end of the table
for (int i = rowCount - 1; i >= 0; i--) {
     tablaudm.getModel().setValueAt("", i, 0);
            tablaudm.getModel().setValueAt("", i, 1);
            tablaudm.getModel().setValueAt("", i, 2);
            tablaudm.getModel().setValueAt("", i, 3);
            tablaudm.getModel().setValueAt("", i, 4);
            tablaudm.getModel().setValueAt("", i, 5);
            tablaudm.getModel().setValueAt("", i, 6);
        
            
    List<Unidaddemedida> unidades=UnidadmedDao.buscaUnidades();
        int row=0;
        
        for(Unidaddemedida unidaddemedida: unidades){
            tablaudm.getModel().setValueAt(unidaddemedida.getIdUm(), row, 0);
            tablaudm.getModel().setValueAt(unidaddemedida.getTipoDeMedida(), row, 1);
            tablaudm.getModel().setValueAt(unidaddemedida.getUnidadmaxima(), row, 2);
            tablaudm.getModel().setValueAt(unidaddemedida.getUnidadminima(), row, 3);
            tablaudm.getModel().setValueAt(unidaddemedida.getLugarmed(), row, 4);
            tablaudm.getModel().setValueAt(unidaddemedida.getFechareg(), row, 5);
            tablaudm.getModel().setValueAt(unidaddemedida.getAreaentrega(), row, 6);
           
            row++;
        }

        this.tablaudm.repaint();
        this.tablaudm.revalidate();
} 
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaentrega;
    private javax.swing.JTextField fechareg;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lugarmed;
    private javax.swing.JTextField nombre;
    private javax.swing.JTable tablaudm;
    private javax.swing.JTextField unidadmax;
    private javax.swing.JTextField unidadmini;
    // End of variables declaration//GEN-END:variables
}
