/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package app.view;

import app.dao.ProductoDao;
import app.model.Producto;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jvazq
 */
public class NewJInternalFrameInventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrameInventario
     */
    public NewJInternalFrameInventario() {
        initComponents();
        ListSelectionModel cellSelectionModel = tablainventario.getSelectionModel();
    cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     ProductoDao ProductoDao = new ProductoDao();
     //DeptoDao deptodao = new DeptoDao();
        
cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
  public void valueChanged(ListSelectionEvent e) {
    String selectedData = null;

    int[] selectedRow = tablainventario.getSelectedRows();
    int[] selectedColumns = tablainventario.getSelectedColumns();

    for (int i = 0; i < selectedRow.length; i++) {
        id.setText( tablainventario.getValueAt(selectedRow[i], 0)+"");
        id.repaint();
        nombre.setText( tablainventario.getValueAt(selectedRow[i], 1)+"");
        nombre.repaint();      
        cantidad.setText( tablainventario.getValueAt(selectedRow[i], 2)+"");
        cantidad.repaint();
        area.setText(tablainventario.getValueAt(selectedRow[i], 3)+"");
        area.repaint();
        tipo.setText(tablainventario.getValueAt(selectedRow[i], 4)+"");
        tipo.repaint();
        unidad.setText(tablainventario.getValueAt(selectedRow[i], 5)+"");
        unidad.repaint();
        precio.setText(tablainventario.getValueAt(selectedRow[i], 6)+"");
        precio.repaint();
        clave.setText(tablainventario.getValueAt(selectedRow[i], 7)+"");
        clave.repaint();
        descripcion.setText(tablainventario.getValueAt(selectedRow[i], 8)+"");
        descripcion.repaint();
        
        
    }
    }
     });

 ProductoDao = new ProductoDao();  
        List<Producto> productos=ProductoDao.buscaProducto();
        int row=0;
        
        for(Producto producto: productos){
     tablainventario.getModel().setValueAt(producto.getIdProducto(), row, 0);
            tablainventario.getModel().setValueAt(producto.getNombre(), row, 1);
            tablainventario.getModel().setValueAt(producto.getCantidad(), row, 2);
            tablainventario.getModel().setValueAt(producto.getPrecio(), row, 3);
            tablainventario.getModel().setValueAt(producto.getArea(), row, 4);
            tablainventario.getModel().setValueAt(producto.getTipo(), row, 5);
            tablainventario.getModel().setValueAt(producto.getUnidaMedida(), row, 6);
            tablainventario.getModel().setValueAt(producto.getClave(), row, 7);
            tablainventario.getModel().setValueAt(producto.getDescripcion(), row, 8);
           
            row++;
        }

        this.tablainventario.repaint();
        this.tablainventario.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablainventario = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nombrer = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nombre = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        area = new javax.swing.JTextField();
        tipo = new javax.swing.JTextField();
        unidad = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        clave = new javax.swing.JTextField();
        descripcion = new javax.swing.JTextField();

        jButton3.setText("jButton3");

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablainventario.setBackground(new java.awt.Color(255, 204, 153));
        tablainventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id producto", "Nombre", "Cantidad", "Precio", "Area", " Tipo", "Unidadmed", "Clave", "Descripcion"
            }
        ));
        tablainventario.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tablainventario);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 790, 140));

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("Inventario");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/imagenes/icons8-producto-nuevo-50.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 70));

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("idproducto");

        nombrer.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        nombrer.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("Cantidad");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Precio");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Area");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("Tipo");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setText("Unidad de medida");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel10.setText("Clave");

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel11.setText("Descripcion");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 56, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombrer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombrer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 170, 250));

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));

        nombre.setBackground(new java.awt.Color(255, 204, 153));

        cantidad.setBackground(new java.awt.Color(255, 204, 153));

        precio.setBackground(new java.awt.Color(255, 204, 153));

        area.setBackground(new java.awt.Color(255, 204, 153));

        tipo.setBackground(new java.awt.Color(255, 204, 153));

        unidad.setBackground(new java.awt.Color(255, 204, 153));

        id.setText("id");

        agregar.setBackground(new java.awt.Color(255, 204, 153));
        agregar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        modificar.setBackground(new java.awt.Color(255, 204, 153));
        modificar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        eliminar.setBackground(new java.awt.Color(255, 204, 153));
        eliminar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        clave.setBackground(new java.awt.Color(255, 204, 153));
        clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveActionPerformed(evt);
            }
        });

        descripcion.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(clave, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(id, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantidad, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(precio, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(area, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unidad, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(id)
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 620, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        
        ProductoDao ProductoDao = new ProductoDao();
      
         
        ProductoDao.insertaRegistro(
                this.nombre.getText(),
                Integer.parseInt(this.precio.getText()),
                Integer.parseInt(this.cantidad.getText()), 
                this.area.getText(), 
                this.tipo.getText(),
                this.unidad.getText(),
                this.clave.getText(),
                this.descripcion.getText());
      
         List<Producto> productos=ProductoDao.buscaProducto();
        int row=0;
        
        for(Producto producto: productos){
            tablainventario.getModel().setValueAt(producto.getIdProducto(), row, 0);
            tablainventario.getModel().setValueAt(producto.getNombre(), row, 1);
            tablainventario.getModel().setValueAt(producto.getCantidad(), row, 2);
            tablainventario.getModel().setValueAt(producto.getPrecio(), row, 3);
            tablainventario.getModel().setValueAt(producto.getArea(), row, 4);
            tablainventario.getModel().setValueAt(producto.getTipo(), row, 5);
            tablainventario.getModel().setValueAt(producto.getUnidaMedida(), row, 6);
            tablainventario.getModel().setValueAt(producto.getClave(), row, 7);
            tablainventario.getModel().setValueAt(producto.getDescripcion(), row, 8);
           
            row++;
        }

        this.tablainventario.repaint();
        this.tablainventario.revalidate();
    }//GEN-LAST:event_agregarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        ProductoDao ProductoDao = new ProductoDao();
      
         
        ProductoDao.updateRegistro(
                this.nombre.getText(),
                Integer.parseInt(this.precio.getText()),
                Integer.parseInt(this.cantidad.getText()), 
                this.area.getText(), 
                this.tipo.getText(),
                this.unidad.getText(),
                this.clave.getText(),
                this.descripcion.getText(),
                Integer.parseInt(id.getText()));
      
         List<Producto> productos=ProductoDao.buscaProducto();
        int row=0;
        
        for(Producto producto: productos){
            tablainventario.getModel().setValueAt(producto.getIdProducto(), row, 0);
            tablainventario.getModel().setValueAt(producto.getNombre(), row, 1);
            tablainventario.getModel().setValueAt(producto.getCantidad(), row, 2);
            tablainventario.getModel().setValueAt(producto.getPrecio(), row, 3);
            tablainventario.getModel().setValueAt(producto.getArea(), row, 4);
            tablainventario.getModel().setValueAt(producto.getTipo(), row, 5);
            tablainventario.getModel().setValueAt(producto.getUnidaMedida(), row, 6);
            tablainventario.getModel().setValueAt(producto.getClave(), row, 7);
            tablainventario.getModel().setValueAt(producto.getDescripcion(), row, 8);
           
            row++;
        }

        this.tablainventario.repaint();
        this.tablainventario.revalidate();
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        
        ProductoDao ProductoDao = new ProductoDao();
      
         
        ProductoDao.deletRegistro(
                Integer.parseInt(id.getText()));
      
        
         DefaultTableModel dm = (DefaultTableModel) tablainventario.getModel();
int rowCount = dm.getRowCount();
//Remove rows one by one from the end of the table
for (int i = rowCount - 1; i >= 0; i--) {
     tablainventario.getModel().setValueAt("", i, 0);
            tablainventario.getModel().setValueAt("", i, 1);
            tablainventario.getModel().setValueAt("", i, 2);
            tablainventario.getModel().setValueAt("", i, 3);
            tablainventario.getModel().setValueAt("", i, 4);
            tablainventario.getModel().setValueAt("", i, 5);
            tablainventario.getModel().setValueAt("", i, 6);
            tablainventario.getModel().setValueAt("", i, 7);
            tablainventario.getModel().setValueAt("", i, 8);
}
        
        
         List<Producto> productos=ProductoDao.buscaProducto();
        int row=0;
        
        for(Producto producto: productos){
            tablainventario.getModel().setValueAt(producto.getIdProducto(), row, 0);
            tablainventario.getModel().setValueAt(producto.getNombre(), row, 1);
            tablainventario.getModel().setValueAt(producto.getCantidad(), row, 2);
            tablainventario.getModel().setValueAt(producto.getPrecio(), row, 3);
            tablainventario.getModel().setValueAt(producto.getArea(), row, 4);
            tablainventario.getModel().setValueAt(producto.getTipo(), row, 5);
            tablainventario.getModel().setValueAt(producto.getUnidaMedida(), row, 6);
            tablainventario.getModel().setValueAt(producto.getClave(), row, 7);
            tablainventario.getModel().setValueAt(producto.getDescripcion(), row, 8);
           
            row++;
        }

        this.tablainventario.repaint();
        this.tablainventario.revalidate();
    }//GEN-LAST:event_eliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTextField area;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField clave;
    private javax.swing.JTextField descripcion;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel nombrer;
    private javax.swing.JTextField precio;
    private javax.swing.JTable tablainventario;
    private javax.swing.JTextField tipo;
    private javax.swing.JTextField unidad;
    // End of variables declaration//GEN-END:variables
}
