/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package app.view;

import app.dao.DetallesVentaDao;
import app.dao.ProductoDao;
import app.model.Detalleventa;
import app.model.Producto;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apple
 */
public class VentaPublico extends javax.swing.JInternalFrame {

    private JFrame main;
    private Integer rowSeleccionado;

    /**
     * Creates new form VentaPublico
     */
    public VentaPublico() {
        initComponents();
    }

    /**
     * Creates new form VentaPublico
     */
    public VentaPublico(JFrame main) {
        initComponents();
        this.main = main;

        tableDetalle.setRowSelectionAllowed(true);
        //tableDetalle.setCellSelectionEnabled(true);
        ListSelectionModel cellSelectionModel = tableDetalle.getSelectionModel();
        cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                //String selectedData = null;

                int[] selectedRow = tableDetalle.getSelectedRows();
                int[] selectedColumns = tableDetalle.getSelectedColumns();

                for (int i = 0; i < selectedRow.length; i++) {
                    for (int j = 0; j < selectedColumns.length; j++) {
                       // selectedData = (String) tableDetalle.getValueAt(selectedRow[i], selectedColumns[j]);
                        rowSeleccionado = selectedRow[i];
                        botonEliminar.setEnabled(true);
                    }
                }
                //System.out.println("Selected: " + selectedData);
            }

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDetalle = new javax.swing.JTable();
        agregarProducto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        subtotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        iva = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        botonEliminar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Venta al publico");

        jLabel1.setText("Vendedor:");

        jLabel2.setText("Vendedor:");

        tableDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cve", "producto", "unidad", "precio unitario", "cantidad", "total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableDetalle);

        agregarProducto.setText("Agregar producto");
        agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoActionPerformed(evt);
            }
        });

        jLabel3.setText("subtotal:");

        subtotal.setText("0.0");
        subtotal.setEnabled(false);
        subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotalActionPerformed(evt);
            }
        });

        jLabel4.setText("IVA:");

        iva.setText("0.0");
        iva.setEnabled(false);

        jLabel5.setText("Total");

        total.setText("0.0");
        total.setEnabled(false);

        botonEliminar.setText("Eliminar producto");
        botonEliminar.setEnabled(false);
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        jButton2.setText("Cofirmar venta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar venta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iva, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarProducto)
                    .addComponent(botonEliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoActionPerformed
        // TODO add your handling code here:
        Producto p = new Producto();
        AgregaProducto ap = new AgregaProducto(this.main, true, p);

        ap.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
               
                DefaultTableModel model = (DefaultTableModel) tableDetalle.getModel();

                Vector row = new Vector();
                row.add(ap.getProductoSleccionado().getCve());
                row.add(ap.getProductoSleccionado().getNombre());
                row.add(ap.getProductoSleccionado().getUnidaMedida());
                row.add(ap.getProductoSleccionado().getPrecio());
                row.add(ap.getProductoSleccionado().getCantidad());
                row.add(ap.getProductoSleccionado().getCantidad() * ap.getProductoSleccionado().getPrecio());

                model.addRow(row);
//            

                calculaTotales();
                tableDetalle.repaint();
                tableDetalle.revalidate();

            }
        });

        p = ap.showDialog();

        //  ap.setVisible(true);

    }//GEN-LAST:event_agregarProductoActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:

        Object[] options = {"Si",
            "No"};
        int n = JOptionPane.showOptionDialog(this.rootPane,
                "Deseas eliminar el producto seleccionado?",
                "Confirma",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[1]);
        System.out.println("elimoinar: " + this.rowSeleccionado + "option: " + n);

        if (n == 0) {
            DefaultTableModel model = (DefaultTableModel) tableDetalle.getModel();
            model.removeRow(this.rowSeleccionado);
            this.botonEliminar.setEnabled(false);

        }
        calculaTotales();

    }//GEN-LAST:event_botonEliminarActionPerformed

    private void subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        List<Detalleventa> detalleVentaList= new ArrayList<>();
        DetallesVentaDao detallesVentaDao= new DetallesVentaDao();
        
        for (int i = 0; i < tableDetalle.getRowCount(); i++) {  // Loop through the rows
            Detalleventa detalleventa= new Detalleventa();
            detalleventa.setCantidadProducto(Integer.valueOf(tableDetalle.getValueAt(i, 4).toString()));
            detalleventa.setCostoTotal(Float.valueOf(tableDetalle.getValueAt(i, 5).toString()));
            detalleVentaList.add(detalleventa);
            
        }
        
            Float sub= Float.valueOf(this.subtotal.getText());
            Float iva=  Float.valueOf(this.iva.getText());
            Float total= Float.valueOf(this.total.getText());
        
        detallesVentaDao.insertaVenta(total, iva, sub, WIDTH, detalleVentaList);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        Object[] options = {"Si",
            "No"};

        int n = JOptionPane.showOptionDialog(this.rootPane,
                "Deseas cancelar la venta?",
                "Confirma",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[1]);

        if (n == 0) {
           this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void calculaTotales() {

        DefaultTableModel model = (DefaultTableModel) tableDetalle.getModel();

        Object[] columnData = new Object[tableDetalle.getRowCount()];  // One entry for each row
        Object[] rowData = new Object[tableDetalle.getRowCount()];

        Float subtotal = 0f;
        //recorre la tabla y suma la columna 5 y lo acumula en la var subtotal
        for (int i = 0; i < tableDetalle.getRowCount(); i++) {  // Loop through the rows
            subtotal += Float.valueOf(tableDetalle.getValueAt(i, 5).toString());
        }

        System.out.println("subtotal: " + String.valueOf(subtotal));
        System.out.println("subtotal: " + String.valueOf(subtotal * 0.16));
        System.out.println("subtotal: " + String.valueOf(subtotal * 1.16));

        this.subtotal.setText(String.valueOf(subtotal));
        this.iva.setText(String.valueOf(Math.round(subtotal * 0.16)));
        this.total.setText(String.valueOf(Math.round(subtotal * 1.16)));

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarProducto;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JTextField iva;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTable tableDetalle;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
