/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.view;

import app.dao.DetallesVentaDao;
import app.model.Detalleventa;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jvazq
 */
public class ventasPanel extends javax.swing.JPanel {

    /**
     * Creates new form ventasPanel
     */
    public ventasPanel() {
        initComponents();
        
        ListSelectionModel cellSelectionModel = tablaventas.getSelectionModel();
    cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     DetallesVentaDao DetallesVentaDao = new DetallesVentaDao();
    
        
cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
  public void valueChanged(ListSelectionEvent e) {
    String selectedData = null;

    int[] selectedRow = tablaventas.getSelectedRows();
    int[] selectedColumns = tablaventas.getSelectedColumns();

    for (int i = 0; i < selectedRow.length; i++) {
        id.setText( tablaventas.getValueAt(selectedRow[i], 0)+"");
        id.repaint();
        costototal.setText( tablaventas.getValueAt(selectedRow[i], 1)+"");
        costototal.repaint();      
        cantidad.setText( tablaventas.getValueAt(selectedRow[i], 2)+"");
        cantidad.repaint();
        ventaid.setText(tablaventas.getValueAt(selectedRow[i], 3)+"");
        ventaid.repaint();
        productoid.setText(tablaventas.getValueAt(selectedRow[i], 4)+"");
        productoid.repaint();
       
    }
    }
     });

 DetallesVentaDao = new DetallesVentaDao();  
        List<Detalleventa> detalles=DetallesVentaDao.buscaVentas();
        int row=0;
        
        for(Detalleventa Detalleventa: detalles){
            tablaventas.getModel().setValueAt(Detalleventa.getDetalleId(), row, 0);
            tablaventas.getModel().setValueAt(Detalleventa.getCostoTotal(), row, 1);
            tablaventas.getModel().setValueAt(Detalleventa.getCantidadProducto(), row, 2);
            tablaventas.getModel().setValueAt(Detalleventa.getVentaId(), row, 3);
            tablaventas.getModel().setValueAt(Detalleventa.getIdProducto(), row, 4);
           
           
            row++;
        }

        this.tablaventas.repaint();
        this.tablaventas.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaventas = new javax.swing.JTable();
        eliminar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ventaid = new javax.swing.JTextField();
        productoid = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        costototal = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Detalles Ventas ");

        tablaventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "detalle id ", "costo total ", "cantidad", "venta id", "producto id"
            }
        ));
        jScrollPane1.setViewportView(tablaventas);

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        jLabel2.setText("detalle id");

        jLabel3.setText("venta id");

        jLabel4.setText("producto id");

        jLabel5.setText("cantidad");

        jLabel6.setText("costo total");

        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });

        costototal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costototalActionPerformed(evt);
            }
        });

        id.setText("id");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eliminar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(206, 206, 206)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(29, 29, 29)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ventaid, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(productoid)
                                        .addComponent(cantidad)
                                        .addComponent(costototal)
                                        .addComponent(id, javax.swing.GroupLayout.Alignment.LEADING)))))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ventaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(productoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(costototal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminar)
                    .addComponent(modificar)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        
         DetallesVentaDao DetallesVentaDao = new DetallesVentaDao();
      
         
        DetallesVentaDao.updateRegistro(
               
                
                Integer.parseInt(this.costototal.getText()),
                Integer.parseInt(this.cantidad.getText()),
                Integer.parseInt(this.ventaid.getText()),
                Integer.parseInt(this.productoid.getText()),
                
                Integer.parseInt(id.getText()));
      
          List<Detalleventa> detalles=DetallesVentaDao.buscaVentas();
        int row=0;
        
         for(Detalleventa Detalleventa: detalles){
            tablaventas.getModel().setValueAt(Detalleventa.getDetalleId(), row, 0);
            tablaventas.getModel().setValueAt(Detalleventa.getCostoTotal(), row, 1);
            tablaventas.getModel().setValueAt(Detalleventa.getCantidadProducto(), row, 2);
            tablaventas.getModel().setValueAt(Detalleventa.getVentaId(), row, 3);
            tablaventas.getModel().setValueAt(Detalleventa.getIdProducto(), row, 4);
           
           
            row++;
        }

        this.tablaventas.repaint();
        this.tablaventas.revalidate();
    }//GEN-LAST:event_modificarActionPerformed

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    private void costototalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costototalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costototalActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        
        DetallesVentaDao DetallesVentaDao = new DetallesVentaDao();
      
         
        DetallesVentaDao.deletRegistro(
                Integer.parseInt(id.getText()));
      
        
         DefaultTableModel dm = (DefaultTableModel) tablaventas.getModel();
int rowCount = dm.getRowCount();
//Remove rows one by one from the end of the table
for (int i = rowCount - 1; i >= 0; i--) {
     tablaventas.getModel().setValueAt("", i, 0);
            tablaventas.getModel().setValueAt("", i, 1);
            tablaventas.getModel().setValueAt("", i, 2);
            tablaventas.getModel().setValueAt("", i, 3);
            tablaventas.getModel().setValueAt("", i, 4);
     
}
        
        
         List<Detalleventa> detalles=DetallesVentaDao.buscaVentas();
         
        int row=0;
        
        for(Detalleventa Detalleventa: detalles){
           tablaventas.getModel().setValueAt(Detalleventa.getDetalleId(), row, 0);
            tablaventas.getModel().setValueAt(Detalleventa.getCostoTotal(), row, 1);
            tablaventas.getModel().setValueAt(Detalleventa.getCantidadProducto(), row, 2);
            tablaventas.getModel().setValueAt(Detalleventa.getVentaId(), row, 3);
            tablaventas.getModel().setValueAt(Detalleventa.getIdProducto(), row, 4);
           
            row++;
        }

        this.tablaventas.repaint();
        this.tablaventas.revalidate();
    }//GEN-LAST:event_eliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DetallesVentaDao DetallesVentaDao = new DetallesVentaDao();
      
         
        DetallesVentaDao.insertaRegistro(
               
                
                Integer.parseInt(this.costototal.getText()),
                Integer.parseInt(this.cantidad.getText()),
                Integer.parseInt(this.ventaid.getText()),
                Integer.parseInt(this.productoid.getText()));
                
          List<Detalleventa> detalles=DetallesVentaDao.buscaVentas();
        int row=0;
        
         for(Detalleventa Detalleventa: detalles){
            tablaventas.getModel().setValueAt(Detalleventa.getDetalleId(), row, 0);
            tablaventas.getModel().setValueAt(Detalleventa.getCostoTotal(), row, 1);
            tablaventas.getModel().setValueAt(Detalleventa.getCantidadProducto(), row, 2);
            tablaventas.getModel().setValueAt(Detalleventa.getVentaId(), row, 3);
            tablaventas.getModel().setValueAt(Detalleventa.getIdProducto(), row, 4);
           
           
            row++;
        }

        this.tablaventas.repaint();
        this.tablaventas.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField costototal;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField productoid;
    private javax.swing.JTable tablaventas;
    private javax.swing.JTextField ventaid;
    // End of variables declaration//GEN-END:variables
}
