/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto;

import com.mycompany.proyecto.dao.DeptoDao;
import com.mycompany.proyecto.dao.EmpleadoDao;
import com.mycompany.proyecto.dao.HorarioDao;
import com.mycompany.proyecto.model.Departamento;
import com.mycompany.proyecto.model.Empleado;
import com.mycompany.proyecto.model.Horario;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ferna
 */
public class CRUDDepto extends javax.swing.JPanel {

    /**
     * Creates new form CRUDDepto
     */
    public CRUDDepto() {
        initComponents();

        ListSelectionModel cellSelectionModel = tablaDepto.getSelectionModel();
        cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        HorarioDao horarioDao = new HorarioDao();

        cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                String selectedData = null;

                int[] selectedRow = tablaDepto.getSelectedRows();
                int[] selectedColumns = tablaDepto.getSelectedColumns();

                for (int i = 0; i < selectedRow.length; i++) {

                    depart.setText(tablaDepto.getValueAt(selectedRow[i], 0) + "");
                    depart.repaint();
                    namedepart.setText(tablaDepto.getValueAt(selectedRow[i], 1) + "");
                    namedepart.repaint();

                }

                System.out.println("Selected: " + selectedData);
            }

        });

        DeptoDao deptoDao = new DeptoDao();
        List<Departamento> empleados = deptoDao.buscaDeptos();
        int row = 0;

        for (Departamento departamento : empleados) {
            tablaDepto.getModel().setValueAt(departamento.getDepartId(), row, 0);
            tablaDepto.getModel().setValueAt(departamento.getNombreDepto(), row, 1);

            row++;
        }

        this.tablaDepto.repaint();
        this.tablaDepto.revalidate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDepto = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        depart = new javax.swing.JTextField();
        namedepart = new javax.swing.JTextField();
        botonActualizar = new javax.swing.JButton();
        botonCrea = new javax.swing.JButton();
        botonDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(91, 149, 206));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DEPARTAMENTO");

        tablaDepto.setBackground(new java.awt.Color(200, 200, 223));
        tablaDepto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "DEPART_ID", "DEPART_NOMBRE"
            }
        ));
        jScrollPane1.setViewportView(tablaDepto);

        jLabel2.setText("DEPART_ID");

        jLabel3.setText("DEPART_NOMBRE");

        depart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departActionPerformed(evt);
            }
        });

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        botonCrea.setText("Crear");
        botonCrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCreaActionPerformed(evt);
            }
        });

        botonDelete.setText("Borrar");
        botonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(namedepart, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(depart, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(109, 109, 109)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonDelete)
                    .addComponent(botonActualizar)
                    .addComponent(botonCrea))
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(botonActualizar)
                        .addGap(24, 24, 24)
                        .addComponent(botonCrea)
                        .addGap(18, 18, 18)
                        .addComponent(botonDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(depart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(namedepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDeleteActionPerformed
        // TODO add your handling code here:
        DeptoDao deptoDao = new DeptoDao();

        Integer idEmpleado = Integer.valueOf(this.depart.getText());

        deptoDao.deleteRegistro(idEmpleado);
        DefaultTableModel dm = (DefaultTableModel) tablaDepto.getModel();
        int rowCount = dm.getRowCount();
//Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            tablaDepto.getModel().setValueAt("", i, 0);
            tablaDepto.getModel().setValueAt("", i, 1);

        }

        List<Departamento> empleados = deptoDao.buscaDeptos();
        int row = 0;

        for (Departamento departamento : empleados) {
            tablaDepto.getModel().setValueAt(departamento.getDepartId(), row, 0);
            tablaDepto.getModel().setValueAt(departamento.getNombreDepto(), row, 1);

            row++;
        }

        this.tablaDepto.repaint();
        this.tablaDepto.revalidate();
    }//GEN-LAST:event_botonDeleteActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        // TODO add your handling code here:
        DeptoDao deptoDao = new DeptoDao();

        Integer idEmpleado = Integer.valueOf(this.depart.getText());

        deptoDao.updateRegistro(idEmpleado, this.namedepart.getText());

        List<Departamento> empleados = deptoDao.buscaDeptos();
        int row = 0;

        for (Departamento departamento : empleados) {
            tablaDepto.getModel().setValueAt(departamento.getDepartId(), row, 0);
            tablaDepto.getModel().setValueAt(departamento.getNombreDepto(), row, 1);

            row++;
        }

        this.tablaDepto.repaint();
        this.tablaDepto.revalidate();

    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonCreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCreaActionPerformed

        DeptoDao deptoDao = new DeptoDao();

        Integer idEmpleado = Integer.valueOf(this.depart.getText());

        deptoDao.insertaRegistro(idEmpleado, this.namedepart.getText());

        List<Departamento> empleados = deptoDao.buscaDeptos();
        int row = 0;

        for (Departamento departamento : empleados) {
            tablaDepto.getModel().setValueAt(departamento.getDepartId(), row, 0);
            tablaDepto.getModel().setValueAt(departamento.getNombreDepto(), row, 1);

            row++;
        }

        this.tablaDepto.repaint();
        this.tablaDepto.revalidate();

        // TODO add your handling code here:
    }//GEN-LAST:event_botonCreaActionPerformed

    private void departActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonCrea;
    private javax.swing.JButton botonDelete;
    private javax.swing.JTextField depart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namedepart;
    private javax.swing.JTable tablaDepto;
    // End of variables declaration//GEN-END:variables
}
