/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto;

import com.mycompany.proyecto.dao.DeptoDao;
import com.mycompany.proyecto.dao.EmpleadoDao;
import com.mycompany.proyecto.dao.HorarioDao;
import com.mycompany.proyecto.dao.RegistroDao;
import com.mycompany.proyecto.model.Departamento;
import com.mycompany.proyecto.model.Empleado;
import com.mycompany.proyecto.model.Horario;
import com.mycompany.proyecto.model.Registro;
import com.mycompany.proyecto.model.Rol;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ferna
 */
public class CRUDEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form CRUDEmpleado
     */
    public CRUDEmpleado() {
        initComponents();
      ListSelectionModel cellSelectionModel = tablaEmpleados.getSelectionModel();
    cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     EmpleadoDao empleadoDao = new EmpleadoDao();
 DeptoDao deptodao = new DeptoDao();
        HorarioDao horarioDao= new HorarioDao();
        
cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
  public void valueChanged(ListSelectionEvent e) {
    String selectedData = null;

    int[] selectedRow = tablaEmpleados.getSelectedRows();
    int[] selectedColumns = tablaEmpleados.getSelectedColumns();

    for (int i = 0; i < selectedRow.length; i++) {
        
        empleadoID.setText( tablaEmpleados.getValueAt(selectedRow[i], 3)+"");
        empleadoID.repaint();
        nombre.setText(tablaEmpleados.getValueAt(selectedRow[i], 0)+"");
        nombre.repaint();
        apellidoPaterno.setText(tablaEmpleados.getValueAt(selectedRow[i], 1)+"");
        apellidoPaterno.repaint();
        apellidoMaterno.setText(tablaEmpleados.getValueAt(selectedRow[i], 2)+"");
        apellidoMaterno.repaint();
        passwordd.setText(tablaEmpleados.getValueAt(selectedRow[i], 6)+"");
        passwordd.repaint();
        
        Integer rolId= Integer.valueOf(tablaEmpleados.getValueAt(selectedRow[i], 5)+"");
        comboRol.setSelectedItem(rolId==1?"Administrador":"Empleado");
        Integer deptoId= Integer.valueOf(tablaEmpleados.getValueAt(selectedRow[i], 4)+"");
        Departamento depto=deptodao.buscaDepartamento(deptoId);
        Integer horarioId= Integer.valueOf(tablaEmpleados.getValueAt(selectedRow[i], 7)+"");
        
        
        Horario horario=horarioDao.buscaHorario(horarioId);
        comboDepto.getModel().setSelectedItem(depto);
        comboHorario.getModel().setSelectedItem(horario);
        comboDepto.repaint();
        comboRol.repaint();
        comboHorario.repaint();

    }
    
    
    
    System.out.println("Selected: " + selectedData);
  }

});

   
        
        List<Departamento> departamentos= deptodao.buscaDeptos();
      
         List<Horario> horarios= horarioDao.buscaHorario();
        
       for(Departamento departamento:departamentos)
         comboDepto.addItem(departamento);
       
       
        
       comboDepto.repaint();
       comboDepto.revalidate();
    
  for(Horario horario:horarios)
         comboHorario.addItem(horario);
       
       
        
       comboHorario.repaint();
       comboHorario.revalidate();       
    
      empleadoDao = new EmpleadoDao();  
        List<Empleado> empleados=empleadoDao.buscaEmpleados();
        int row=0;
        
        for(Empleado empleado: empleados){
            tablaEmpleados.getModel().setValueAt(empleado.getNombre(), row, 0);
            tablaEmpleados.getModel().setValueAt(empleado.getPrimerA(), row, 1);
            tablaEmpleados.getModel().setValueAt(empleado.getSegunA(), row, 2);
            tablaEmpleados.getModel().setValueAt(empleado.getId(), row, 3);
            tablaEmpleados.getModel().setValueAt(empleado.getDepart(), row, 4);
            tablaEmpleados.getModel().setValueAt(empleado.getRolID(), row, 5);
            tablaEmpleados.getModel().setValueAt(empleado.getPassword(), row, 6);
            tablaEmpleados.getModel().setValueAt(empleado.getHorarioID(), row, 7);
           
            row++;
        }

        this.tablaEmpleados.repaint();
        this.tablaEmpleados.revalidate();
    
    
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPasswordField1 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        empleadoID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellidoPaterno = new javax.swing.JTextField();
        apellidoMaterno = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        comboRol = new javax.swing.JComboBox<>();
        comboDepto = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        comboHorario = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        passwordd = new javax.swing.JTextField();

        jScrollPane2.setViewportView(jEditorPane1);

        jPasswordField1.setText("jPasswordField1");

        setBackground(new java.awt.Color(91, 149, 206));

        tablaEmpleados.setBackground(new java.awt.Color(200, 200, 223));
        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "ApellidoP", "ApellidoM", "ID", "Departamento", "Rol", "Password", "Horario"
            }
        ));
        jScrollPane1.setViewportView(tablaEmpleados);

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID empleado");

        empleadoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadoIDActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido Paterno");

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido Materno");

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Depto");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rol");

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        apellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoPaternoActionPerformed(evt);
            }
        });

        apellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoMaternoActionPerformed(evt);
            }
        });

        jButton3.setText("Crear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Borrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EMPLEADOS");

        comboRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado" }));

        comboDepto.setModel(new javax.swing.DefaultComboBoxModel<>( ));
        comboDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDeptoActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Horario");

        comboHorario.setModel(new javax.swing.DefaultComboBoxModel<>());

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("password");

        passwordd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passworddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(268, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(apellidoPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(apellidoMaterno)
                                    .addComponent(comboRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboDepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordd))
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(jButton4))
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(empleadoID, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(186, 186, 186))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)))))
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empleadoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(apellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(passwordd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboDepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(31, 31, 31)
                        .addComponent(jButton3)
                        .addGap(27, 27, 27)
                        .addComponent(jButton4)
                        .addGap(75, 75, 75)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
                 EmpleadoDao empleadoDao= new EmpleadoDao();
         
         Integer idEmpleado= Integer.valueOf(this.empleadoID.getText());
         Integer idRol= this.comboRol.getSelectedItem().toString().equals("Administrador")?1:2;
         Horario horarioSelected= (Horario)this.comboHorario.getSelectedItem();
         Departamento deptoSelected= (Departamento)this.comboDepto.getSelectedItem();
         
         
         empleadoDao.updateRegistro(idEmpleado, this.nombre.getText(),this.apellidoPaterno.getText(),this.apellidoMaterno.getText(),idRol , deptoSelected.getDepartId(), this.passwordd.getText(), horarioSelected.getHorarioid());
      
         List<Empleado> empleados=empleadoDao.buscaEmpleados();
        int row=0;
        
        for(Empleado empleado: empleados){
            tablaEmpleados.getModel().setValueAt(empleado.getNombre(), row, 0);
            tablaEmpleados.getModel().setValueAt(empleado.getPrimerA(), row, 1);
            tablaEmpleados.getModel().setValueAt(empleado.getSegunA(), row, 2);
            tablaEmpleados.getModel().setValueAt(empleado.getId(), row, 3);
            tablaEmpleados.getModel().setValueAt(empleado.getDepart(), row, 4);
            tablaEmpleados.getModel().setValueAt(empleado.getRolID(), row, 5);
            tablaEmpleados.getModel().setValueAt(empleado.getPassword(), row, 6);
            tablaEmpleados.getModel().setValueAt(empleado.getHorarioID(), row, 7);
           
            row++;
        }

        this.tablaEmpleados.repaint();
        this.tablaEmpleados.revalidate();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        EmpleadoDao empleadoDao= new EmpleadoDao();
         Integer idEmpleado= Integer.valueOf(this.empleadoID.getText());
        empleadoDao.deletRegistro(idEmpleado);
        
        DefaultTableModel dm = (DefaultTableModel) tablaEmpleados.getModel();
int rowCount = dm.getRowCount();
//Remove rows one by one from the end of the table
for (int i = rowCount - 1; i >= 0; i--) {
    tablaEmpleados.getModel().setValueAt("", i, 0);
            tablaEmpleados.getModel().setValueAt("", i, 1);
            tablaEmpleados.getModel().setValueAt("", i, 2);
            tablaEmpleados.getModel().setValueAt("", i, 3);
            tablaEmpleados.getModel().setValueAt("", i, 4);
            tablaEmpleados.getModel().setValueAt("", i, 5);
            tablaEmpleados.getModel().setValueAt("", i, 6);
            tablaEmpleados.getModel().setValueAt("", i, 7);
}
        
        List<Empleado> empleados=empleadoDao.buscaEmpleados();
        int row=0;
        for(Empleado empleado: empleados){
            tablaEmpleados.getModel().setValueAt(empleado.getNombre(), row, 0);
            tablaEmpleados.getModel().setValueAt(empleado.getPrimerA(), row, 1);
            tablaEmpleados.getModel().setValueAt(empleado.getSegunA(), row, 2);
            tablaEmpleados.getModel().setValueAt(empleado.getId(), row, 3);
            tablaEmpleados.getModel().setValueAt(empleado.getDepart(), row, 4);
            tablaEmpleados.getModel().setValueAt(empleado.getRolID(), row, 5);
            tablaEmpleados.getModel().setValueAt(empleado.getPassword(), row, 6);
            tablaEmpleados.getModel().setValueAt(empleado.getHorarioID(), row, 7);
           
            row++;
        }

        
        this.tablaEmpleados.repaint();
        this.tablaEmpleados.revalidate();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         EmpleadoDao empleadoDao= new EmpleadoDao();
         
         Integer idEmpleado= Integer.valueOf(this.empleadoID.getText());
         Integer idRol= this.comboRol.getSelectedItem().toString().equals("Administrador")?1:2;
         Horario horarioSelected= (Horario)this.comboHorario.getSelectedItem();
         Departamento deptoSelected= (Departamento)this.comboDepto.getSelectedItem();
         
         
         empleadoDao.insertaRegistro(idEmpleado, this.nombre.getText(),this.apellidoPaterno.getText(),this.apellidoMaterno.getText(),idRol , deptoSelected.getDepartId(), this.passwordd.getText(), horarioSelected.getHorarioid());
      
         List<Empleado> empleados=empleadoDao.buscaEmpleados();
        int row=0;
        
        for(Empleado empleado: empleados){
            tablaEmpleados.getModel().setValueAt(empleado.getNombre(), row, 0);
            tablaEmpleados.getModel().setValueAt(empleado.getPrimerA(), row, 1);
            tablaEmpleados.getModel().setValueAt(empleado.getSegunA(), row, 2);
            tablaEmpleados.getModel().setValueAt(empleado.getId(), row, 3);
            tablaEmpleados.getModel().setValueAt(empleado.getDepart(), row, 4);
            tablaEmpleados.getModel().setValueAt(empleado.getRolID(), row, 5);
            tablaEmpleados.getModel().setValueAt(empleado.getPassword(), row, 6);
            tablaEmpleados.getModel().setValueAt(empleado.getHorarioID(), row, 7);
           
            row++;
        }

        this.tablaEmpleados.repaint();
        this.tablaEmpleados.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void empleadoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleadoIDActionPerformed

    private void comboDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDeptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDeptoActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void apellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoPaternoActionPerformed

    private void apellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoMaternoActionPerformed

    private void passworddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passworddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passworddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoMaterno;
    private javax.swing.JTextField apellidoPaterno;
    private javax.swing.JComboBox<Departamento> comboDepto;
    private javax.swing.JComboBox<Horario> comboHorario;
    private javax.swing.JComboBox<String> comboRol;
    private javax.swing.JTextField empleadoID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField passwordd;
    private javax.swing.JTable tablaEmpleados;
    // End of variables declaration//GEN-END:variables

private Integer depto;
private Integer roll;
private Integer horarioo;


}
