/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto;

import com.mycompany.proyecto.dao.DeptoDao;
import com.mycompany.proyecto.dao.HorarioDao;
import com.mycompany.proyecto.model.Departamento;
import com.mycompany.proyecto.model.Horario;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ferna
 */
public class CRUDHorario extends javax.swing.JPanel {

    /**
     * Creates new form CRUDHorario
     */
    public CRUDHorario() {
        initComponents();
                ListSelectionModel cellSelectionModel = jTable1.getSelectionModel();
        cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        HorarioDao horarioDao = new HorarioDao();

        cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                String selectedData = null;

                int[] selectedRow = jTable1.getSelectedRows();
                int[] selectedColumns = jTable1.getSelectedColumns();

                for (int i = 0; i < selectedRow.length; i++) {

                    empleadoid.setText(jTable1.getValueAt(selectedRow[i], 0) + "");
                    empleadoid.repaint();
                    horaentrada.setText(jTable1.getValueAt(selectedRow[i], 1) + "");
                    horaentrada.repaint();
                    horasalida.setText(jTable1.getValueAt(selectedRow[i], 2) + "");
                    horasalida.repaint();

                }

                System.out.println("Selected: " + selectedData);
            }

        });

        List<Horario> empleados = horarioDao.buscaHorario();
        int row = 0;

        for (Horario horario : empleados) {
            jTable1.getModel().setValueAt(horario.getHorarioid(), row, 0);
            jTable1.getModel().setValueAt(horario.getHoraEntra(), row, 1);
            jTable1.getModel().setValueAt(horario.getHoraSalid(), row, 2);

            row++;
        }

        this.jTable1.repaint();
        this.jTable1.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        empleadoid = new javax.swing.JTextField();
        horaentrada = new javax.swing.JTextField();
        horasalida = new javax.swing.JTextField();
        actuali = new javax.swing.JButton();
        crear = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(91, 149, 206));

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HORARIO");

        jLabel2.setText("emp_id");

        jLabel3.setText("Hora Entrada");

        jLabel4.setText("Hora Salida");

        empleadoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadoidActionPerformed(evt);
            }
        });

        actuali.setText("Actualizar");
        actuali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiActionPerformed(evt);
            }
        });

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(200, 200, 223));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "emp_id", "HoraEntra", "HoraSali"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(horaentrada, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(empleadoid)
                            .addComponent(horasalida))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(actuali)
                            .addComponent(crear)
                            .addComponent(borrar))
                        .addGap(124, 124, 124))))
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(actuali)
                        .addGap(22, 22, 22)
                        .addComponent(crear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(borrar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empleadoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(horaentrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(horasalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actualiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualiActionPerformed
        // TODO add your handling code here:
    HorarioDao horarioDao = new HorarioDao();

        Integer idEmpleado = Integer.valueOf(this.empleadoid.getText());

        horarioDao.updateRegistro(idEmpleado,horaentrada.getText(),horasalida.getText());

        List<Horario> empleados = horarioDao.buscaHorario();
        int row = 0;

        for (Horario horario : empleados) {
            jTable1.getModel().setValueAt(horario.getHorarioid(), row, 0);
            jTable1.getModel().setValueAt(horario.getHoraEntra(), row, 1);
            jTable1.getModel().setValueAt(horario.getHoraSalid(), row, 2);

            row++;
        }

        this.jTable1.repaint();
        this.jTable1.revalidate();

    }//GEN-LAST:event_actualiActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        // TODO add your handling code here:
        HorarioDao horarioDao = new HorarioDao();

        Integer idEmpleado = Integer.valueOf(this.empleadoid.getText());

        horarioDao. insertaRegistro(idEmpleado,horaentrada.getText(),horasalida.getText());

        List<Horario> empleados = horarioDao.buscaHorario();
        int row = 0;

        for (Horario horario : empleados) {
            jTable1.getModel().setValueAt(horario.getHorarioid(), row, 0);
            jTable1.getModel().setValueAt(horario.getHoraEntra(), row, 1);
            jTable1.getModel().setValueAt(horario.getHoraSalid(), row, 2);

            row++;
        }

        this.jTable1.repaint();
        this.jTable1.revalidate();
    }//GEN-LAST:event_crearActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
         HorarioDao horarioDao = new HorarioDao();

        Integer idEmpleado = Integer.valueOf(this.empleadoid.getText());

        horarioDao.deleteRegistro(idEmpleado);
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        int rowCount = dm.getRowCount();
//Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            jTable1.getModel().setValueAt("", i, 0);
            jTable1.getModel().setValueAt("", i, 1);
jTable1.getModel().setValueAt("", i, 2);
        }

       List<Horario> empleados = horarioDao.buscaHorario();
        int row = 0;

        for (Horario horario : empleados) {
            jTable1.getModel().setValueAt(horario.getHorarioid(), row, 0);
            jTable1.getModel().setValueAt(horario.getHoraEntra(), row, 1);
            jTable1.getModel().setValueAt(horario.getHoraSalid(), row, 2);

            row++;
        }

        this.jTable1.repaint();
        this.jTable1.revalidate();
    }//GEN-LAST:event_borrarActionPerformed

    private void empleadoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadoidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleadoidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actuali;
    private javax.swing.JButton borrar;
    private javax.swing.JButton crear;
    private javax.swing.JTextField empleadoid;
    private javax.swing.JTextField horaentrada;
    private javax.swing.JTextField horasalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
